### ISSUE TITLE
Czech letters not working

### ISSUE THREAD

**Issue by ZirixCZ** [WailedParsley36/MountBlueCheats#1]
Text written by the "Zadávání textu v konzoli" does not contain the letter 'ř'
When using "OCR Ctení" , it does contain that letter, but the feature does not work overall.

**Comment by WailedParsley36** [comment]
Yeah I know that's a problem that I can't repair, because I am using Third Party OCR System named IronOCR which has the bug with the letters.
Also if you have problem with the letters on Windows. Try looking into the display settings and under Scale you will need to set it to 100%

**Comment by ZirixCZ** [comment]
That helped. Closing the issue.
